MONGODB_HOST: mongodb-{{ env }}.bloombear.fun
REDIS_HOST: redis-{{ env }}.bloombear.fun
CATALOGUE_HOST: catalogue-{{ env }}.bloombear.fun
CART_HOST: cart-{{ env }}.bloombear.fun
USER_HOST: user-{{ env }}.bloombear.fun
MYSQL_HOST: mysql-{{ env }}.bloombear.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.bloombear.fun
PAYMENT_HOST: payment-{{ env }}.bloombear.fun
SHIPPING_HOST: shipping-{{ env }}.bloombear.fun