- name: Copying mongodb repo file
  ansible.builtin.copy:
    src: ./mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing mongodb package
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Allowing remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting and enabling service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
