- name: installing mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: starting and enabling the mysql server
  ansible.builtin.service:
    enabled: yes
    name: mysqld
    state: started

- name: setting up the root password
  vars:
    MYSQL_ROOT_PASSWORD: RoboShop@1
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{MYSQL_ROOT_PASSWORD}}"