- name: installing mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: starting and enabling the mysql server
  ansible.builtin.service:
    enabled: yes
    name: mysqld
    state: started

- name: setting up the root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{mysql_root_password}}"