# Creating roboshop system user
# idempotent unlike the normal shell command
- name: creating roboshop system user
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop System user
    system: true
    shell: /sbin/nologin
    home: /app

- name: deleting the app directory
  ansible.builtin.file:
    path: /app
    state: absent
  
- name: creating the app directory
  ansible.builtin.file:
    path: /app
    state: directory
  
- name: deleting the {{component}} code file in tmp directory
  ansible.builtin.file:
    path: /tmp/{{component}}.zip
    state: absent

- name: downloading {{component}} application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: /tmp/{{component}}.zip

- name: unzipping {{component}} application
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes
